baseURL = "https://harashuu.dev/"
languageCode = "ja-jp"
title = "harashuu.dev"
theme = "PaperMod"
hasCJKLanguage = true

enableRobotsTXT = true

[params]
  math = true
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true
  TocOpen = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[menu]
  [[menu.main]]
      name = "About"
      url = "/about/"
      weight = 10
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 3

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]  # Searchç”¨
